# Generated by Django 4.1.2 on 2022-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('context', models.CharField(max_length=500)),
            ],
        ),
    ]
