name: test_Django
on: [pull_request]
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r qotd/requirements.txt
      - run: python qotd/manage.py test qotd/
