name: test_Django
on: [pull_request, push]
jobs:
  test_project:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r qotd/requirements
      - run: python qotd/manage.py test
